### ISSUE TITLE
Rails integration

### ISSUE THREAD

**Issue by DevinRiley** [DevinRiley/disque_jockey#3]
@StevenJL it would be good to get your thoughts on this.

I looked into ActiveJob integration today and have a few lessons learned:
- To let people use their ActiveJob classes with DisqueJockey we'd have to PR into rails with a new QueueAdapter class for DisqueJockey.  Its really straightforward to write the adapter (I wrote one today) but we are unlikely to get merged into rails unless the project has some traction.
- ActiveJob integration is kinda janky even in existing queueing backends like Sneakers so I'm not as attracted to the integration thing anymore.
- Its _really_ easy to set up an app/workers directory that DisqueJockey pulls from and just run a separate process from, e.g. a foreman Procfile, alongside your rails app.  This is basically still how it works even if you do have ActiveJob integration a la sidekiq or sneakers.

So, my proposal is I just add instructions in the README on how to put DisqueJockey workers into a Rails app and have a toy rails app repo that people can look at / clone down to see a concrete example.

**Comment by StevenJL** [comment]
@DevinRiley That sounds like a great idea. Can you wanna create another repo that's a toy rails app with a couple of disque_jockey workers in the app/workers directory? Once that's up we can play around with that and put a link to it on the  README for disque_jockey.
